### ISSUE TITLE
Unable to change any other input except for Text in the Report Box

### ISSUE THREAD

**Issue by GeneralPoxter** [Pinafore/karl-flashcards-web-app#12]
This issue is unique to trying to report a card in the Study All tab. Reporting a card from the Browse Facts tab works fine.

Deleting text from input boxes for Answer, Category, and Identifier works, but trying to insert text inserts the text into the Text input box only.
Strangely, refreshing the tab seems to fix the issue, so I was only able to document [one instance](https://streamable.com/suh5w6) of this occurring.

**Comment by Nonameentered** [comment]
I believe this was an issue from an old version before better updating features were implemented. I believe this is why a refresh fixed this issue.
